version: '3.2'

services:
  broker:
    image: rabbitmq:3.6.10-management-alpine
    ports:
      - "15672:15672"

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile

  wishlist:
    build:
      context: ./wishlist
      dockerfile: Dockerfile
