// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/customer.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/customer.proto

It has these top-level messages:
	Customer
	GetCustomerRequest
	GetCustomerResponse
	SaveCustomerRequest
	SaveCustomerResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Customer struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto1.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Customer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCustomerRequest struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *GetCustomerRequest) Reset()                    { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()               {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type GetCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *GetCustomerResponse) Reset()                    { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()               {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type SaveCustomerRequest struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *SaveCustomerRequest) Reset()                    { *m = SaveCustomerRequest{} }
func (m *SaveCustomerRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveCustomerRequest) ProtoMessage()               {}
func (*SaveCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SaveCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type SaveCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *SaveCustomerResponse) Reset()                    { *m = SaveCustomerResponse{} }
func (m *SaveCustomerResponse) String() string            { return proto1.CompactTextString(m) }
func (*SaveCustomerResponse) ProtoMessage()               {}
func (*SaveCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto1.RegisterType((*Customer)(nil), "proto.Customer")
	proto1.RegisterType((*GetCustomerRequest)(nil), "proto.GetCustomerRequest")
	proto1.RegisterType((*GetCustomerResponse)(nil), "proto.GetCustomerResponse")
	proto1.RegisterType((*SaveCustomerRequest)(nil), "proto.SaveCustomerRequest")
	proto1.RegisterType((*SaveCustomerResponse)(nil), "proto.SaveCustomerResponse")
}

func init() { proto1.RegisterFile("proto/customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2e, 0x2d, 0x2e, 0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x03, 0x73, 0x85, 0x58, 0xc1,
	0x94, 0x92, 0x1e, 0x17, 0x87, 0x33, 0x54, 0x42, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x39, 0x88, 0x29, 0x33, 0x45, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x72, 0xe4, 0x12, 0x72, 0x4f, 0x2d, 0x81,
	0x69, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xd2, 0xe6, 0xe2, 0x80, 0x19, 0x0f, 0xd6,
	0xcf, 0x6d, 0xc4, 0x0f, 0xb1, 0x46, 0x0f, 0xae, 0x12, 0xae, 0x40, 0xc9, 0x89, 0x4b, 0x18, 0xc5,
	0x88, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x92, 0xcd, 0x08, 0x4e, 0x2c, 0x4b, 0xa5, 0xc8, 0x1d,
	0xce, 0x5c, 0x22, 0xa8, 0x66, 0x90, 0xe1, 0x10, 0xa3, 0x09, 0x8c, 0x5c, 0xfc, 0x30, 0xe1, 0xe0,
	0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x1b, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x49, 0xa8,
	0x2e, 0xcc, 0xf0, 0x92, 0x92, 0xc2, 0x26, 0x05, 0xb5, 0xde, 0x9e, 0x8b, 0x05, 0xe4, 0x2c, 0x21,
	0x98, 0x1a, 0x2c, 0xfe, 0x94, 0x92, 0xc6, 0x2a, 0x07, 0x31, 0xc0, 0xc9, 0x20, 0x4a, 0x2f, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xbf, 0x2c, 0xb1, 0x38, 0x33, 0x27, 0xb3,
	0x52, 0xb7, 0x44, 0x3f, 0x37, 0x33, 0xb9, 0x28, 0xbf, 0xa4, 0x28, 0x31, 0x33, 0x0f, 0x9e, 0x16,
	0xf4, 0xc1, 0xc6, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x36,
	0xa6, 0x78, 0x2a, 0x02, 0x00, 0x00,
}
